dist: trusty

git:
  depth: 500

language: node_js

node_js:
  - lts/*

before_install:
  - curl -sSL https://raw.githubusercontent.com/cljs-oss/canary/master/scripts/install-canary.sh | bash
  - wget https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh
  - mv boot.sh boot && chmod a+x boot && sudo mv boot /usr/local/bin

script:
  - boot > /dev/null
  - boot test
